#ifndef VKGL_GL_DISABLE_VERTEX_ATTRIB_ARRAY_H
#define VKGL_GL_DISABLE_VERTEX_ATTRIB_ARRAY_H

#include "OpenGL/types.h"

VKGL_API void VKGL_APIENTRY glDisableVertexAttribArray(GLuint index);

#endif /* VKGL_GL_DISABLE_VERTEX_ATTRIB_ARRAY_H */